name: Setup PR for code review

on:
  pull_request_target:
    types: [opened, reopened]

permissions: write-all

jobs:

  assign:
    runs-on: ubuntu-latest    
    steps:
     - name: Parsing your PR title for lab number
       env:
          TITLE: ${{ github.event.pull_request.title }}
       run: |
        SUB='Лаб.'
        for VAR in 1 2 3 4
        do
            if (echo $TITLE | grep -iqF "$SUB$VAR" )|| (echo $TITLE | grep -iqF "$SUB $VAR"); then
                echo "LABEL=Lab $VAR" >> "$GITHUB_ENV"
                break
            fi      
        done
        for VAR in 6211 6212 6213 6214
        do
            if (echo $TITLE | grep -iqF "$VAR" ); then
                echo "GROUP=$VAR" >> "$GITHUB_ENV"
                break
            fi      
        done

     - name: Checking your lab number
       run: |
        if [[ $LABEL == '' ]]; then
            echo "Your PR caption is not composed correctly"
            exit 1
        fi
        echo Your number was parsed correctly - ${{ env.LABEL }}

     - name: Checking your group number
       run: |
        if [[ $GROUP == '' ]]; then
            echo "Your PR caption is not composed correctly"
            exit 1
        fi
        echo Your group was parsed correctly - ${{ env.GROUP }}
     
     - name: Setting PR labels
       uses: actions-ecosystem/action-add-labels@v1
       with:
        labels: |
           ${{ env.LABEL }}
           In progress
        
     - name: Setting reviewer & assignee for lab 1 & 2
       if: env.LABEL == 'Lab 1' || env.LABEL == 'Lab 2'
       uses: hkusu/review-assign-action@v1
       with:
          assignees: ${{ github.event.pull_request.user.login }} 
          reviewers: KopVas
          
     - name: Setting reviewer & assignee for lab 3 & 4
       if: (env.LABEL == 'Lab 3' || env.LABEL == 'Lab 4') && ( env.GROUP == '6211' || env.GROUP == '6212' )
       uses: AveryCameronUofR/add-reviewer-gh-action@1.0.3
       with:
          reviewers: "ladyitsecurity"    

     - name: Setting reviewer & assignee for lab 3 & 4
       if: (env.LABEL == 'Lab 3' || env.LABEL == 'Lab 4') && ( env.GROUP == '6213' || env.GROUP == '6214' )
       uses: AveryCameronUofR/add-reviewer-gh-action@1.0.3
       with:
          reviewers: "Daria-creator-lab"    

     - name: Display results
       run: echo '${{ steps.assign.outputs.result }}'
